### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by elypter** [truongsinh/node-evercookie#4]
im getting this error

niemand@Anya ~ $ npm install --save evercookie
npm WARN saveError ENOENT: no such file or directory, open '/home/niemand/package.json'
/home/niemand
└─┬ evercookie@0.3.0 
  └─┬ cookie-parser@1.1.0 
    ├── cookie@0.1.2 
    └── cookie-signature@1.0.3 

npm WARN enoent ENOENT: no such file or directory, open '/home/niemand/package.json'
npm WARN niemand No description
npm WARN niemand No repository field.
npm WARN niemand No README data
npm WARN niemand No license field.

**Comment by truongsinh** [comment]
you need to have `package.json` file in your own project, you can try `npm init` (ref https://docs.npmjs.com/cli/init)
